# Generated by Django 3.2.6 on 2021-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_passport_ssn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ssn_number',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
    ]
