# Generated by Django 3.2.6 on 2021-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_medicalinfo_appoinment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='bp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
