# Generated by Django 3.2.6 on 2021-08-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visacenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='visacenter',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
