# Generated by Django 3.2.6 on 2021-08-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_visacenter_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacenter',
            name='ssn_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visacenter',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
