# Generated by Django 3.2.6 on 2021-08-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210821_0701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisaCenter',
            new_name='Visa',
        ),
    ]
