# Generated by Django 3.2.6 on 2021-12-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211206_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='police_verification_record',
        ),
    ]
