# Generated by Django 3.2.6 on 2021-12-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_passport_police_verification_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='birth_certificate_number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='citizenship_by_birth',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='pressent_address',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='ssn_number',
        ),
    ]
